org: salvedy
app: aws-node-express-api-project
service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DYNAMODB_BIOGRAPHY_TABLE: ${self:service}-biographyTable-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-biographyTable-${sls:stage}


functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
  createBiography:
  handler: createBiography.createBiography
  events:
    - httpApi:
        path: /biography
        method: post

resources:
  Resources:
    BiographyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-biographyTable-${sls:stage}

